* basics

** Dependencies
   - docker-compose
   - babashka (https://github.com/babashka/babashka/)  2.9 or more

** Usage
   mba wraps docker-compose, and all commands it does not understand
   are passed to the underlying docker-compose.

   - =mba config == docker-compose -f tmp.yml config= . will show what
     is it about to generate

   By default, it will share ports, but in the future, it will not
   share them, and make you use =--port 3000:3000= flags, so you can
   jail things better.

   - =mba up= . creates the stack
   - =mba down=. destroys the stack
   - =mba shell=. gives a shell inside the main metabase container
   - =mba dbconsole=. console into the app-db

   If it is ran in the metabase directory, it will run the
   .devcontainer image, so you should enter it and run the commands
   manually to start the app.

   SUPERHACK: ENV vars are passed around at the moment, to have the commands available
   #+begin_src bash
     mba up
     mba shell
     eval $MBA_CLI

     mba shell
     eval $MBA_YARN_BUiLD
   #+end_src
   so hacky, amazing.

   - mba --help may help you with the commands and option, but for the
     values, explore src/main.clj
   - to pass flags to docker-compose , or any command underlying mba,
     the way to pass as a parameter to inside is with =--=: =mba
     --app-db postgres logs -- -f=


* requirements to make it work as a dev env

** node
  Change the webpack command to --host 0.0.0.0

     "build-watch": "yarn && webpack --watch",
  - "build-hot": "yarn && NODE_ENV=hot webpack-dev-server --progress",
  - "build-hot": "yarn && NODE_ENV=hot webpack-dev-server --progress --host 0.0.0.0",
    "build-stats": "yarn && webpack --json > stats.json",
** clojure
    lein repl :headless :port 7888

** EE flags

** cypress


https://github.com/microsoft/vscode-dev-containers/tree/master/containers/java-8

* dalton++

https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en
https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden?hl=en
